### ISSUE TITLE
Nvidia prime configuration for hybrid graphics

### ISSUE THREAD

**Issue by paolomainardi** [paolomainardi/archlinux-ansible-provisioner#83]
Currently we are not fully supporting hybrid graphic systems (intel/nvidia).
https://github.com/paolomainardi/archlinux-ansible-provisioner/blob/main/playbooks/roles/nvidia/tasks/main.yml#L36 we are just installing `nvidia-prime` which is not enough.

What we would like to achieve instead:

1. Boot the system in hybrid mode (intel and nvidia enabled)
2. Run discrete card one when connected to external monitors
3. Run integrated one when not using external monitors - in this scenario discrete card is powered off (https://wiki.archlinux.org/title/PRIME#PCI-Express_Runtime_D3_(RTD3)_Power_Management)

cc @grota

**Comment by paolomainardi** [comment]
Maybe we should use this one https://github.com/Askannz/optimus-manager ?

**Comment by grota** [comment]
yeah the scenario outlined looks good, I'll test/look into it/study as soon as I get around it :)

**Comment by paolomainardi** [comment]
System76 is the most advanced distro taking in charge this problem: https://support.system76.com/articles/graphics-switch-pop/
